### ISSUE TITLE
Duplicate call of start function

### ISSUE THREAD

**Issue by florianhartung** [DLR-FT/wasm-interpreter#31]
This was introduced in https://github.com/DLR-FT/wasm-interpreter/pull/18 and I'm unsure if this change was done on purpose.
https://github.com/DLR-FT/wasm-interpreter/blob/25f07b92ceeeed6d25b3385fd0e91235aa5f74e8/src/execution/mod.rs#L62-L65

**Comment by florianhartung** [comment]
@nerodesu017

**Comment by nerodesu017** [comment]
Not intentional, got added when rebasing, will fix right away.
