### ISSUE TITLE
Binary file section ordering problem

### ISSUE THREAD

**Issue by nerodesu017** [DLR-FT/wasm-interpreter#6]
As stated in the [WebAssembly Spec](https://webassembly.github.io/spec/core/binary/modules.html):

> Section ids do not always correspond to the [order of sections](https://webassembly.github.io/spec/core/binary/modules.html#binary-module) in the encoding of a module.

From what I'm seeing in [validation](https://github.com/DLR-FT/wasm-interpreter/blob/main/src/validation/mod.rs), the order is hardcoded, or am I wrong?

I propose a rewrite of it, where we dynamically figure out the type based on the type id extracted from the section.

**Comment by florianhartung** [comment]
Yes, the order is hardcoded on purpose.
I think the quoted statement from the WASM Spec may be misleading here.
It just states that section ids do not correspond to the order of sections. It does not make any statements about the order itself, which is defined in one of the next sections ([see here](https://webassembly.github.io/spec/core/binary/modules.html#binary-module)).

The actual order of section ids is:
```
0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 12, 0, 10, 0, 11, 0
```
Note that the `data count section (id=12)` is out of order.
