### ISSUE TITLE
Missing documentation for `crate::validation::ValidationStack::assert_val_types(...)`

### ISSUE THREAD

**Issue by george-cosma** [DLR-FT/wasm-interpreter#84]
ValidationStack has almost everything documented - nice! Although there is a missing spot. I noticed it just now, after merging the PR related to it. I **assume** it asserts that the value stack contains exactly the provided values, but I would like to get a confirmation from the author(s).

**Comment by florianhartung** [comment]
Your assumption is correct. I already had the docs written but apparently I was too slow to force push it to that PR before it was merged 😴
