### ISSUE TITLE
Tables - RefCell, UnsafeCell or just UNSAFE?

### ISSUE THREAD

**Issue by nerodesu017** [DLR-FT/wasm-interpreter#94]
Related to PR #90 something, it's the Dev/Elements that will be added.
Context:
`table.copy` instruction needs to copy from one table to another and having a simple Vec<TableInst> leads us to having a mutable and an immutable reference to the Vec.

**Comment by george-cosma** [comment]
Note: Proposed solution is  to use UnsafeCell with our own safety checks for both speed and relative safety. Alternative would be to have a feature guard between the two implementations.

TODO: measure the performance impact
